name: fantastic-spoon
version: 0.1.0

dependencies:
- aeson
- base
- bytestring
- cryptonite
- http-types
- monad-logger
- persistent
- persistent-postgresql
- persistent-template
- resourcet
- text
- yesod
- yesod-auth
- yesod-static

ghc-options:
- -Wall
- -Werror

executable:
  main: Main.hs
